version: '3'
services:
  redis:
    image: redis:latest
    volumes:
      - ./redis:/data
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: mhcamillow/node:latest
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '80:8080'
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - redis
  redis-insight:
    image: redislabs/redisinsight:latest
    volumes: 
      - ./redis-insight:/db
    ports:
      - '8001:8001'
    depends_on: 
      - redis
